using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


public class English : Language
{
    public override Dictionary<string, string> buildDictionary()
    {
        Dictionary<string, string> englishDict = new Dictionary<string, string>();
        englishDict.Add("lizard_name", "Lizards");
        englishDict.Add("predator_name", "Predators");
        englishDict.Add("competitor_name", "Competitors");
        englishDict.Add("food_name", "Lizard's Food Source");
        englishDict.Add("plant_name", "Vegetal food");
        englishDict.Add("insect_name", "Insects");
        englishDict.Add("fruit_plant_name", "Fruitful plant");
        englishDict.Add("hunger", "Hunger");
        englishDict.Add("age", "Age");
        englishDict.Add("predation", "Predation");
        englishDict.Add("insolation", "Insolation");
        englishDict.Add("years", "Years");
        englishDict.Add("controls", "Controls");
        englishDict.Add("or", "or");
        englishDict.Add("main_menu", "Main Menu");
        englishDict.Add("restart", "Restart");
        englishDict.Add("next", "Next stage");
        englishDict.Add("congratulations", "Congratulations!");
        englishDict.Add("game_over", "Game Over!");
        englishDict.Add("state", "State");
        englishDict.Add("name", "Name");
        englishDict.Add("macambira", "Macambira");
        englishDict.Add("sapucaia", "Sapucaia");
        englishDict.Add("murici", "Murici");
        englishDict.Add("sapo", "Frog");
        englishDict.Add("raposa", "Fox");
        englishDict.Add("gato", "Wild cat");
        englishDict.Add("rest", "Rest");
        englishDict.Add("trying_mate", "Trying to mate");
        englishDict.Add("looking_food", "Looking for food");
        englishDict.Add("trying_eat", "Trying to eat");
        englishDict.Add("looking_shadow", "Looking for shadows");
        englishDict.Add("running_shadow", "Runnint to shadow");
        englishDict.Add("cooling", "Cooling");
        englishDict.Add("running_predator", "Running from predators");
        englishDict.Add("hiding", "Hiding");
        englishDict.Add("running_competitor", "Running from competitor");
        englishDict.Add("figthing", "Figthing");
        englishDict.Add("first_phase_obj", "1. Increase your Lizard population to {0} or more before {1} years. Currently: {2} </color>/{3}");
        englishDict.Add("first_phase_end_txt", "You grew your population to {0} or more in {1} and {2} months!");
        englishDict.Add("second_phase_obj", "1. Keep your population of Lizards below {0} individuals for {1} years. Currently: {2} </color>/ {0}");
        englishDict.Add("third_phase_obj", "1. Keep your population of Lizards below {0} individuals until the year {1}. Currently: {2} </color>/{0}");
        englishDict.Add("fourth_phase_obj", "1. Increase your Lizard population above {0} in {1} years. Currently: {2} </color>/{0}");
        englishDict.Add("sand_box_obj_1", "2. Keep your population under control. It cannot pass {0} individual nor it can be reduced to {1} or less. Currently: {2} </color>");
        englishDict.Add("sand_box_obj_2", "1. Increase your Lizard population to {0} or more. Currently: {1} </color>/{0}");
        englishDict.Add("sand_box_end_txt", "You managed to keep your population under control for {0} yers and {1} months");
        englishDict.Add("brush_button_txt_1", "Fruitless plant");
        englishDict.Add("has_insect", "Has Insects");
        englishDict.Add("has_hideout", "Hideout for lizards");
        englishDict.Add("has_shadows", "Generate shadows");
        englishDict.Add("initial_insects", "Starting insect count");
        englishDict.Add("energy_by_insects", "Energy by insect");
        englishDict.Add("time_of_life", "Life span");
        englishDict.Add("reproduction", "Reproduction");
        englishDict.Add("descendants_per_day", "New individuals per day");
        englishDict.Add("frog_description", "Compete with lizards for insects");
        englishDict.Add("hunt_speed", "Hunt speed");
        englishDict.Add("fruits_by_hour", "Fruit by hour");
        englishDict.Add("production_radius", "Fruit generation radius");
        englishDict.Add("fruit_energy", "Fruit energy");
        englishDict.Add("fox_description", "Hunts the lizards, controlling their population.");
        englishDict.Add("cat_description", "Cats are fast and hunt lizards with high frequency. Use them carefully.");
        englishDict.Add("death_causes", "Death causes");
        englishDict.Add("tutorial_1_text_1", "Hi, Welcome to Calangos 3");
        englishDict.Add("tutorial_1_text_2", "I'm professor X and I'm here to help you learn!");
        englishDict.Add("tutorial_1_text_3", "You will watch out for a population of lizards");
        englishDict.Add("tutorial_1_text_4", "In this tutorial, we need to make sure that it grows over {0} individuals!");
        englishDict.Add("tutorial_1_text_5", "But first, we need to learn more about the game");
        englishDict.Add("tutorial_1_text_6", "As I said, this is your population");
        englishDict.Add("tutorial_1_text_7", "This is your Biocoin counter, it shows you how much Biocoin you have");
        englishDict.Add("tutorial_1_text_8", "Your Biocoin increases in time");
        englishDict.Add("tutorial_1_text_9", "You can use the Biocoin to add new species of plants in the environment");
        englishDict.Add("tutorial_1_text_10", "Here, you can choose which species to add");
        englishDict.Add("tutorial_1_text_11", "Each species has unique carcteristics and a Biocoin cost");
        englishDict.Add("tutorial_1_text_12", "You can only add a species if you have the required Biocoin");
        englishDict.Add("tutorial_1_text_13", "Lets start! Add some vegetation to feed your lizards");
        englishDict.Add("tutorial_1_text_14", "Good Game!");
        englishDict.Add("tutorial_2_text_1", "Well done! Your population has grown.");
        englishDict.Add("tutorial_2_text_2", "But be carefull so it won't grow too much!");
        englishDict.Add("tutorial_2_text_3", "There is too much food and the population will grow unbalanced!");
        englishDict.Add("tutorial_2_text_4", "Some species compete for food and can keep your population under control");
        englishDict.Add("tutorial_2_text_5", "Insert some competitors to control the lizard population");
        englishDict.Add("tutorial_3_text_1", "Atention! Your population keeps growing...");
        englishDict.Add("tutorial_3_text_2", "We need more radical measures!");
        englishDict.Add("tutorial_3_text_3", "You can add predators to reduce the population of lizards");
        englishDict.Add("tutorial_4_text_1", "Whatch out! The temperature is too high");
        englishDict.Add("tutorial_4_text_2", "We need to provide shadows for the lizards");
        englishDict.Add("tutorial_4_text_3", "Too much sun exposure can be letal");
        englishDict.Add("tutorial_4_text_4", "Insert plants that project shadows to avoid their death");
        englishDict.Add("tutorial_sand_box_text_1", "Congratulations! You now know everything about Calangos 3");
        englishDict.Add("tutorial_sand_box_text_2", "Now, let's test what you just learned");
        englishDict.Add("tutorial_sand_box_text_3", "Grow your population and keep it stable as long as you can!");
        englishDict.Add("gui_dificulty_tittle", "Choose the difficulty");
        englishDict.Add("gui_dificulty_option_1", "Easy");
        englishDict.Add("gui_dificulty_option_2", "Moderate");
        englishDict.Add("gui_dificulty_option_3", "Hard");
        englishDict.Add("gui_language_tittle", "Escolha a Língua");
        englishDict.Add("gui_tutorial_button_1", "Tutorial 1");
        englishDict.Add("gui_tutorial_button_2", "Tutorial 2");
        englishDict.Add("gui_tutorial_button_3", "Tutorial 3");
        englishDict.Add("gui_tutorial_button_4", "Tutorial 4");
        englishDict.Add("gui_tutorial_sand_box", "Challenge mode");
        return englishDict;
    }
}

