using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Portuguese : Language
{
    public override Dictionary<string, string> buildDictionary()
    {
        Dictionary<string, string> portugueseDict = new Dictionary<string, string>();
        portugueseDict.Add("lizard_name", "Calangos");
        portugueseDict.Add("predator_name", "Predadores");
        portugueseDict.Add("competitor_name", "Competidores");
        portugueseDict.Add("food_name", "Vegetação");
        portugueseDict.Add("plant_name", "Plantas");
        portugueseDict.Add("insect_name", "Insetos");
        portugueseDict.Add("fruit_plant_name", "Plantas frutíferas");
        portugueseDict.Add("hunger", "Fome");
        portugueseDict.Add("age", "Idade");
        portugueseDict.Add("predation", "Predação");
        portugueseDict.Add("insolation", "Insolação");
        portugueseDict.Add("years", "Anos");
        portugueseDict.Add("controls", "Controles");
        portugueseDict.Add("or", "ou");
        portugueseDict.Add("main_menu", "Menu principal");
        portugueseDict.Add("restart", "Recomeçar");
        portugueseDict.Add("next", "Próxima Fase");
        portugueseDict.Add("congratulations", "Parabéns!");
        portugueseDict.Add("game_over", "Fim de jogo");
        portugueseDict.Add("state", "Estado");
        portugueseDict.Add("name", "Nome");
        portugueseDict.Add("macambira", "Macambira");
        portugueseDict.Add("sapucaia", "Sapucaia");
        portugueseDict.Add("murici", "Murici");
        portugueseDict.Add("sapo", "Sapo");
        portugueseDict.Add("raposa", "Raposa");
        portugueseDict.Add("gato", "Gato selvgem");
        portugueseDict.Add("rest", "Repouso");
        portugueseDict.Add("trying_mate", "Tentando acasalar");
        portugueseDict.Add("looking_food", "Procurando comida");
        portugueseDict.Add("trying_eat", "Tentando comer");
        portugueseDict.Add("looking_shadow", "Procurando sombra");
        portugueseDict.Add("running_shadow", "Correndo para a sombra");
        portugueseDict.Add("cooling", "Refrescando");
        portugueseDict.Add("running_predator", "Fugindo de predadores");
        portugueseDict.Add("hiding", "Escondendo-se");
        portugueseDict.Add("running_competitor", "Fugindo de competidor");
        portugueseDict.Add("figthing", "Batalhando");
        portugueseDict.Add("first_phase_obj", "1. Aumentar a população de lagartos para {0} ou mais antes de {1} anos. Atualmente: {2} </color>/{3}");
        portugueseDict.Add("first_phase_end_txt", "Você conseguiu crescer sua população para {0} ou mais em por {1} anos e {2} meses!");
        portugueseDict.Add("second_phase_obj", "1. Manter a população de lagartos abaixo de {0} indivíduos por {1} anos. Atualmente: {2} </color>/ {0}");
        portugueseDict.Add("third_phase_obj", "1. Manter a população abaixo de {0} indivíduos até o {1}º ano. Atualmente: {2} </color>/{0}");
        portugueseDict.Add("fourth_phase_obj", "1. Aumentar a população de lagartos acima dos {0} em até {1} anos. Atualmente: {2} </color>/{0}");
        portugueseDict.Add("sand_box_obj_1", "1. Mantenha a população sobre controle. Ela não pode passar de {0} nem reduzir para menos de {1}. Atualmente: {2} </color>");
        portugueseDict.Add("sand_box_obj_2", "1. Aumentar a população de lagartos para {0} ou mais. Atualmente: {1} </color>/{0}");
        portugueseDict.Add("sand_box_end_txt", "Você conseguiu manter uma população estável por {0} anos e {1} meses!");
        portugueseDict.Add("brush_button_txt_1", "Planta não frutífera");
        portugueseDict.Add("has_insect", "Contém insetos");
        portugueseDict.Add("has_hideout", "Esconderijo contra predadores");
        portugueseDict.Add("has_shadows", "Projeta sombras");
        portugueseDict.Add("initial_insects", "Quantidade inicial de insetos");
        portugueseDict.Add("energy_by_insects", "Energia por inseto");
        portugueseDict.Add("time_of_life", "Tempo de vida");
        portugueseDict.Add("reproduction", "Reprodução");
        portugueseDict.Add("descendants_per_day", "filhos por dia");
        portugueseDict.Add("frog_description", "Disputam os alimentos com os lagartos.");
        portugueseDict.Add("hunt_speed", "Velocidade de caça");
        portugueseDict.Add("fruits_by_hour", "Frutas por hora");
        portugueseDict.Add("production_radius", "Raio de alcançe");
        portugueseDict.Add("fruit_energy", "Energia da fruta");
        portugueseDict.Add("fox_description", "Caçam os lagartos, controlado sua população.");
        portugueseDict.Add("cat_description", "São rápidos e caçam com frequência. Use com cuidado!");
        portugueseDict.Add("death_causes", "Causas de morte");
        portugueseDict.Add("tutorial_1_text_1", "Oi, Bem-vido ao Calangos ");
        portugueseDict.Add("tutorial_1_text_2", "Eu sou o professor X e estou aqui para lhe ajudar a aprender!");
        portugueseDict.Add("tutorial_1_text_3", "Você vai cuidar de uma população de lagartos ");
        portugueseDict.Add("tutorial_1_text_4", "Neste tutorial, devemos garantir que ela aumente de tamanho até atingir {0} indivíduos!");
        portugueseDict.Add("tutorial_1_text_5", "Mas antes, vamos aprender mais sobre o jogo ");
        portugueseDict.Add("tutorial_1_text_6", "Como já disse, aqui está sua população ");
        portugueseDict.Add("tutorial_1_text_7", "Este é seu contador de Biomassa, ele mostra quanto você tem de Biomassa no momento");
        portugueseDict.Add("tutorial_1_text_8", "sua biomassa aumenta com o tempo ");
        portugueseDict.Add("tutorial_1_text_9", "Utilizando a Biomassa você pode adicionar novas espécies de plantas ao ambiente ");
        portugueseDict.Add("tutorial_1_text_10", "Aqui voce pode escolher quais espécies adicionar");
        portugueseDict.Add("tutorial_1_text_11", "Cada espécie apresenta característias próprias e tem um custo de biomassa ");
        portugueseDict.Add("tutorial_1_text_12", "Só poderá inserir uma espécie se tiver a biomassa exigida  ");
        portugueseDict.Add("tutorial_1_text_13", "Insira vegetação para alimentar os seus lagartos");
        portugueseDict.Add("tutorial_1_text_14", "Bom jogo!");
        portugueseDict.Add("tutorial_2_text_1", "Muito bem! Sua população cresceu.");
        portugueseDict.Add("tutorial_2_text_2", "Mas, cuidado para ela não crescer demais!");
        portugueseDict.Add("tutorial_2_text_3", "Alimentos estão sobrando e a população irá crescer de forma desequilibrada!");
        portugueseDict.Add("tutorial_2_text_4", "Algumas espécies disputam por alimentos e podem manter sua população controlada");
        portugueseDict.Add("tutorial_2_text_5", "Insira espécies competidoras para controlar o crescimento de lagartos");
        portugueseDict.Add("tutorial_3_text_1", "Atenção! A população de lagartos continua a se expandir...");
        portugueseDict.Add("tutorial_3_text_2", "Precisamos de medidas mais radicais!");
        portugueseDict.Add("tutorial_3_text_3", "Podemos inserir espécies Predadoras para reduzir sua população");
        portugueseDict.Add("tutorial_4_text_1", "Cuidado! A temperatura está muito alta");
        portugueseDict.Add("tutorial_4_text_2", "Precisamos gerar sombras para os lagartos");
        portugueseDict.Add("tutorial_4_text_3", "Muita exposição ao sol pode levar os lagartos a morte!");
        portugueseDict.Add("tutorial_4_text_4", "Insira plantas que projetem sombra para evitar que os lagartos morram");
        portugueseDict.Add("tutorial_sand_box_text_1", "Parabéns! Você agora já sabe tudo sobre o Calangos");
        portugueseDict.Add("tutorial_sand_box_text_2", "Agora vamos testar o que você aprendeu...");
        portugueseDict.Add("tutorial_sand_box_text_3", "Cresça sua população e mantenha-a estável pelo máximo de tempo possivel!");
        portugueseDict.Add("gui_dificulty_tittle", "Escolha a dificuldade");
        portugueseDict.Add("gui_dificulty_option_1", "Fácil");
        portugueseDict.Add("gui_dificulty_option_2", "Moderado");
        portugueseDict.Add("gui_dificulty_option_3", "Difícil");
        portugueseDict.Add("gui_language_tittle", "Choose a language");
        portugueseDict.Add("gui_tutorial_button_1", "Tutorial 1");
        portugueseDict.Add("gui_tutorial_button_2", "Tutorial 2");
        portugueseDict.Add("gui_tutorial_button_3", "Tutorial 3");
        portugueseDict.Add("gui_tutorial_button_4", "Tutorial 4");
        portugueseDict.Add("gui_tutorial_sand_box", "Modo Livre");
        return portugueseDict;
    }
}
